# Generated by Django 5.0.1 on 2024-01-11 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accreditation',
            fields=[
                ('accreditation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('label', models.TextField(null=True)),
                ('text_key', models.TextField(null=True)),
                ('accreditation_url', models.URLField(null=True)),
                ('type', models.TextField(null=True)),
                ('accreditation_description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentAccreditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('have', models.BooleanField()),
                ('accreditation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.accreditation')),
            ],
        ),
        migrations.CreateModel(
            name='EstateAgent',
            fields=[
                ('account_number', models.TextField(primary_key=True, serialize=False)),
                ('agent_name', models.TextField(null=True)),
                ('branch_name', models.TextField(null=True)),
                ('display_address', models.TextField(null=True)),
                ('agent_url', models.URLField(null=True)),
                ('private_developer', models.BooleanField(null=True)),
                ('developer_primary_contact', models.BooleanField(null=True)),
                ('developer', models.BooleanField(null=True)),
                ('agent_tier', models.TextField(null=True)),
                ('agent_enhanced_branding', models.BooleanField(null=True)),
                ('accreditations', models.ManyToManyField(through='backend.AgentAccreditation', to='backend.accreditation')),
            ],
        ),
        migrations.AddField(
            model_name='agentaccreditation',
            name='agent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.estateagent'),
        ),
        migrations.CreateModel(
            name='KeyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.TextField()),
                ('feature_name', models.TextField(null=True)),
                ('feature_text', models.TextField(null=True)),
            ],
            options={
                'unique_together': {('property_id', 'feature_name')},
            },
        ),
        migrations.CreateModel(
            name='PropertyData',
            fields=[
                ('property_id', models.TextField(primary_key=True, serialize=False)),
                ('display_address', models.TextField(null=True)),
                ('unit_number', models.TextField(null=True)),
                ('site_number', models.TextField(null=True)),
                ('building_name', models.TextField(null=True)),
                ('house_number', models.TextField(null=True)),
                ('street', models.TextField(null=True)),
                ('town', models.TextField(null=True)),
                ('region', models.TextField(null=True)),
                ('postcode', models.TextField(null=True)),
                ('country', models.TextField(null=True)),
                ('lat', models.DecimalField(decimal_places=10, max_digits=50, null=True)),
                ('long', models.DecimalField(decimal_places=10, max_digits=50, null=True)),
                ('coordinate_accuracy', models.TextField(null=True)),
                ('bedrooms', models.IntegerField(null=True)),
                ('bathrooms', models.IntegerField(null=True)),
                ('receptions', models.IntegerField(null=True)),
                ('property_type', models.TextField(null=True)),
                ('comm_res', models.TextField(null=True)),
                ('sale_type', models.TextField(null=True)),
                ('coming_soon', models.BooleanField(null=True)),
                ('property_style', models.TextField(null=True)),
                ('furnished', models.TextField(null=True)),
                ('date_viewable_from', models.TextField(null=True)),
                ('date_available_from', models.TextField(null=True)),
                ('date_added', models.TextField(null=True)),
                ('open_viewing', models.BooleanField(null=True)),
                ('continuousRelisting', models.BooleanField(null=True)),
                ('auction', models.BooleanField(null=True)),
                ('price_tracker', models.BooleanField(null=True)),
                ('total_images', models.IntegerField(null=True)),
                ('total_videos', models.IntegerField(null=True)),
                ('tagline', models.TextField(null=True)),
                ('brief_text', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('show_home_opening_time', models.TextField(null=True)),
                ('short_listed', models.BooleanField(null=True)),
                ('featurable', models.BooleanField(null=True)),
                ('premium_listing', models.BooleanField(null=True)),
                ('premier_available', models.BooleanField(null=True)),
                ('co_ownership', models.BooleanField(null=True)),
                ('broadband_estimated', models.BooleanField(null=True)),
                ('broadband_max_down', models.TextField(null=True)),
                ('broadband_max_up', models.TextField(null=True)),
                ('broadband_max_bb_down', models.TextField(null=True)),
                ('broadband_max_bb_up', models.TextField(null=True)),
                ('broadband_max_sfbb_down', models.TextField(null=True)),
                ('broadband_max_sfbb_up', models.TextField(null=True)),
                ('broadband_max_ufbb_down', models.TextField(null=True)),
                ('broadband_max_ufbb_up', models.TextField(null=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.estateagent')),
                ('key_features', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.keyfeature')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('scraped_before', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('property_data', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.propertydata')),
            ],
        ),
        migrations.CreateModel(
            name='Views',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.TextField(null=True)),
                ('view_date', models.TextField(null=True)),
                ('unique_views', models.IntegerField(null=True)),
                ('total_views', models.IntegerField(null=True)),
                ('featured', models.BooleanField(null=True)),
                ('bumped', models.BooleanField(null=True)),
                ('published', models.BooleanField(null=True)),
            ],
            options={
                'unique_together': {('property_id', 'view_date')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='agentaccreditation',
            unique_together={('agent_id', 'accreditation_id')},
        ),
        migrations.CreateModel(
            name='ListingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_qualifier', models.TextField(null=True)),
                ('price_suffix', models.TextField(null=True)),
                ('previous_status', models.TextField(null=True)),
                ('price_difference', models.IntegerField(null=True)),
                ('previous_price', models.IntegerField(null=True)),
                ('previous_published', models.BooleanField(null=True)),
                ('status_change', models.BooleanField(null=True)),
                ('price_change', models.BooleanField(null=True)),
                ('published_changed', models.BooleanField(null=True)),
                ('status', models.TextField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('update_date', models.TextField(null=True)),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.property')),
            ],
            options={
                'unique_together': {('property_id', 'update_date')},
            },
        ),
    ]
