# Generated by Django 5.0.1 on 2024-01-11 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_keyfeature_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='views',
            name='property_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.property'),
        ),
    ]
