# Generated by Django 5.0.1 on 2024-01-11 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_views_property_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertydata',
            name='key_features',
        ),
        migrations.AlterField(
            model_name='keyfeature',
            name='property_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.property'),
        ),
    ]
