# Generated by Django 5.0.1 on 2024-01-12 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_propertydata_key_features_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='scraped_before',
        ),
        migrations.AlterField(
            model_name='property',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
